@startuml

class Main << (O,#FFD036) Object >>
package projectiles {
class Projectiles << (O,#FFD036) Object >>
class Projectile
}
package places {
class Grid
class Place
}
package mvc {
class MVC
class Model
class Controller
class View
class UIButton
}
package insects {
class Insect
class Ant
class Bee
}
package colony {
class Colony
}

Main *-- MVC
MVC o-- Model
MVC o-- Controller
MVC o-- View
Controller o-- Model
Controller o-- View
View o-- Controller
View *-- "*" UIButton

Model o-- Colony
Model *-- Grid
Model o-- Projectiles

Grid *-- "*" Place
Place *-- "0-1" Ant
Place *-- "*" Bee

Insect o-- Place
Ant o-- Colony

Insect <|-- Ant
Insect <|-- Bee

@enduml
