@startuml

class Projectiles << (O,#FFD036) Object >>
class Projectile
class Insect


Projectile o-right- "1" Insect
Projectiles *-- "*" Projectile


Projectiles : projectiles()
Projectiles : addProjectile()
Projectiles : removeProjectile()
Projectiles : removeUselessProjectiles()
Projectiles : moves()

Projectile : x()
Projectile : y()
Projectile : hasHit()
Projectile : move()
Projectile : hit()


@enduml


